// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestComp: typeof import('./src/components/TestComp.vue')['default']
    TestFolder: typeof import('./src/components/common/TestFolder.vue')['default']
    TestTemplate: typeof import('./src/components/TestTemplate.vue')['default']
  }
}
